### ISSUE TITLE
'OSM Data Report: Visualizing Our Progress'

### ISSUE THREAD

**Issue by tmcw** [tmcw/presentations#8]
With @ericfischer - how do we want to split this up? Part of this will be just exploring the site, doing quick deconstructions of how the visualizations came about. I will make a few slides for some of the things I'm familiar with (the live map, the member-treemap).

**Comment by e-n-f** [comment]
I wish I was better prepared for this. I can talk about the mechanics of how to accumulate total distance over time from the history dump, although it's probably not really very interesting, and can show highlights of the GPS map and the recent edits map. I could talk about mechanism for either of those maps too since I will be for the workshop, but it's probably really off topic for this.

**Comment by tmcw** [comment]
Done in 9a34b714e32ed668eeaf450dba6611213b6e5051
